spring.thymeleaf.mode=LEGACYHTML5
spring.profiles.active=dev
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST}	
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.template.retry.enabled=true
spring.resources.cache.cachecontrol.max-age=10000
spring.resources.cache.cachecontrol.must-revalidate=true
spring.resources.cache.cachecontrol.cache-private= false
spring.resources.cache.cachecontrol.cache-public= true



server.port=9010
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/png
server.compression.min-response-size=1024
server.http2.enabled=true

message.publisher.queue.name=nicu-connect-device-data
message.subscriber.queue.name=device-config-data
message.center.queue.name=rtwo.queue
message.center.queue.history=RTWO.JPN.history.queue
message.dassist.exchange.name=dassist-direct-exchange
message.center.queue.drug.name=RTWO.JPN.drug.name.queue

drivers.path=/connectEngine/driverJarsDump/

center.name=RTWO
center.location=JPN
center.enableTrolley=false
user.secret=password

spring.main.banner-mode=OFF

logging.file.name=/home/monish/Desktop/CIS-Deployment/CIS-Deployment/connectEngine/logs/CE.log
logging.file.max-size=100MB
logging.level.root=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.rtwo.med.device.connect=ERROR
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR