server.port = 9001
server.servlet.context-path=/api
spring.profiles.active= dev
spring.data.mongodb.uri=mongodb://localhost/CRITI-ICU

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

message.exchange.name=dassist-direct-exchange
message.device.configuration.queue=device.configuration.queue
message.patient.create.queue=dassist.patient.create.queue
message.patient.discharge.queue=dassist.patient.discharge.queue
message.patient.update.queue=dassist.patient.update.queue
message.center.details.queue=dassist.center.details.queue
message.update.center.details.queue=dassist.update.center.details.queue
message.bed.delete.queue=dassist.bed.delete.queue
message.manual.history.queue=dassist.manual.history.queue
message.history.queue=dassist.history.queue
message.extend.history.queue=dassist.extend.history.queue
message.vitalsdata.queue = dassist.vitalsdata.queue
message.alarmdata.queue = dassist.alarmdata.queue
message.center.queue.drug.name=RTWO.JPN.drug.name.queue

admin.username=admin
admin.password=Admin@123

jwt.secret=admin@0987iiyerwerqwjkKjhj@$#^askjdasfhkj*&%
jwt.ttl=7000

address = http://127.0.0.1:9010
visaddress = http://127.0.0.1:9012

center.name=RTWO
center.location=JPN

azure.logic.app.url=https://prod-17.centralindia.logic.azure.com
azure.logic.app.api-version=2016-10-01
azure.logic.app.sp=%2Ftriggers%2Fmanual%2Frun
azure.logic.app.sv=1.0
azure.logic.app.sig=JIe-PehghYRzNRgKI9Q1_aSMvtJqEOF6kH41AXII-ro

logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.com.dragger.cis.DragerCISBackend=DEBUG
logging.file.name=C:/CIS-Deployment/CIS LOGS/BE/backend-logs

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

#Mail Sending Configuration
logging.level.org.springframework.mail=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=draggercis@gmail.com
spring.mail.password=Dragger@1234
# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mongodb.embedded.version=3.2.8
spring.mvc.pathmatch.matching-strategy=ant-path-matcher