spring.thymeleaf.mode=LEGACYHTML5
spring.profiles.active=production
spring.resources.cache.cachecontrol.max-age=10000
spring.resources.cache.cachecontrol.must-revalidate=true
spring.resources.cache.cachecontrol.cache-private= false
spring.resources.cache.cachecontrol.cache-public= true
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST}	
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.template.retry.enabled=true



#server.http.port=9012
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/png
server.compression.min-response-size=1024
server.http2.enabled=true

message.publisher.queue.name=nicu-connect-device-data
message.subscriber.queue.name=device-config-data

center.name=RTWO
center.location=JPN
user.secret=password

page.title=ICU Connect

# JitsVideo Meeting Configuration
video.meeting.enabled=false
video.meeting.room.name=Sakra-Hospital-Meeting

spring.main.banner-mode=OFF

logging.file.name=C:/CIS-Deployment/CIS LOGS/VE/deviceVisualizationEngine.log
logging.file.max-size=100MB
logging.level.root=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.rtwo.med.device.connect=ERROR

messages.ack=false
server.port=9013

multi.tenant.history.service.enabled=false
multi.tenant.history.service.uri=http://localhost:9011

